plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
env:
  browser: true
  es2021: true
extends: 
  - airbnb-base
  - plugin:jest/recommended
overrides: []
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: 
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
  import/extensions: 0
  no-param-reassign: 0 # разрешает переназначенеи параметров ( el0, el1 в функции objToString в файле compare.js)