name: testAndLint
on: push
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - name: Deps install
          run: make install
  
        - name: Linter check
          run: make lint

        - name: Jest check
          run: make test        